print(True and True)
print(True and False)
print(False and True)
print(False and False)
print()

print(True or True)
print(True or False)
print(False or True)
print(False or False)
print()

print(not True)
print(not False)
print()

print(not True and False or not False)
print()

print(((not True) and False) or (not False))
print()

print(10 == 10 and 10 != 5)
print(10 > 5 or 10 < 3)
print(not 10 > 5)
print(not 1 is 1.0)
print()

print(bool(1))
print(bool(0))
print(bool(1.5))
print(bool('False'))
print()

print(False and True)
print(False and False)
print(True or True)
print(True or False)
print(True and 'Python')
print('Python' and True)
print('Python' and False)
print(False and 'Python')
print(0 and 'Python')
print(True or 'Python')
print('Python' or True)
print(False or 'Python')
print(0 or 'Python')